[workspace]
resolver = "2"
members = [
    "fib-circuit",
    "prover",
    "verifier",
]

[profile.dev]
opt-level = 3

[workspace.dependencies]
halo2_proofs = "0.3.1"
pasta_curves = "0.5.1"
rand_core = "0.6.4"
serde = "1.0"
bincode = "1.3.3"